name:        cssr
version:     0.0.0.1
synopsis:    Initial project template
description: Please see README.md
category:    Hidden Markov Models
author:      Sam Stites
maintainer:  sam@stites.io
github:      stites/CSSR
license:     BSD
copyright:   2016-2017

ghc-options: -fno-warn-name-shadowing

default-extensions:
  - MultiParamTypeClasses
  - OverloadedStrings
  - PatternSynonyms
  - TypeFamilies
  - ViewPatterns
  - LambdaCase

dependencies:
  - base
  - bytestring
  - containers
  - hashable
  - pipes
  - pipes-bytestring
  - scientific
  - statistics
  - text
  - unordered-containers
  - vector
  - microlens-platform
  - microlens
  - hashtables
  - primitive

library:
  source-dirs: src

executables:
  schema-prediction:
    main: Main.hs
    source-dirs: app
    dependencies:
      - cssr
      - optparse-applicative

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - cssr
      - hspec
      - QuickCheck

  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - cssr
      - doctest
      - QuickCheck

benchmarks:
  bench:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - cssr
      - criterion
      - deepseq
    ghc-options: -O2

